services:
  s3:
    image:  chrislusf/seaweedfs
    environment:
      AWS_ACCESS_KEY_ID: admin
      AWS_SECRET_ACCESS_KEY: secret
      S3_BUCKET: pgups-images
    ports:
      - "8333:8333"
    volumes:
      - weed-data:/data

volumes:
  weed-data:
