[package]
name = "lab-6"
version = "0.1.0"
edition = "2024"

[dependencies]
dialoguer = "0.11.0"
num = "0.4.3"
windows-sys = { version = "0.59.0", features = ["Win32_Security", "Win32_Storage_FileSystem", "Win32_System_IO", "Win32_System_Threading"] }
