services:
  minio:
    image: minio/minio
    ports:
      - "9000:9000"  # MinIO server port
      - "9001:9001"  # MinIO console port
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

volumes:
  minio_data:
