[package]
name = "lab-3"
version = "0.1.0"
edition = "2024"

[dependencies]
dialoguer = "0.11.0"
windows-sys = { version = "0.59.0", features = [
    "Win32_System_Console",
    "Win32_System_Memory",
    "Win32_System_SystemServices" 
] }
