@startuml
'https://plantuml.com/class-diagram
skinparam classAttributeIconSize 0
skinparam genericDisplay old

class Queue<T> {
    -m_first: Node*
    -m_size: size_t

    +size(): size_t
    +toArray(): T*
    +enqueue(data: T)
    +dequeue(): T
    +peek(): T
    +clear()

    -getLast(): Node*
}

class Node <<struct>> {
        +data: T
        +next: Node*
}

Queue +-right.- Node


@enduml