#import "@local/pgups:0.1.0": *

#structural[Перечень сокращений]

- ABI -- Application Binary Interface.
- API -- Application programming interface.
- AoT -- Ahead of Time.
- CLI -- Command Line Interface.
- CPU -- Central Processor Unit.
- CSV -- Comma Separated Values.
- FFI -- Foreign Function Interface.
- FaaS -- Function as a Service.
- GC -- Garbage Collector.
- HTTP -- Hypertext Transfer Protocol.
- IDL -- Interface description language.
- JIT -- Just In Time.
- JSON -- JavaScript Object Notation.
- OCI -- Open Container Initiative.
- RAII -- Resource Acquisition Is Initialization.
- RPS -- Requests Per Second.
- SDK -- Software Development Kit.
- SIMD -- Single Instruction Multiple Data.
- SPA -- Single Page Application.
- SQL -- Structured Query Language.
- SSE -- Server Sent Events.
- TLS -- Transport Level Security.
- WASI -- WebAssembly System Interface.
- WASM -- WebAssembly.
- WIT -- WebAssembly Interface Types.
- ВМ -- Виртуальная машина.
- ЖЦ -- Жизненный цикл.
- ИД -- Индекс доходности.
- НДС -- Налог на добавленную стоимость.
- НР -- Накладные расходы.
- ОЗП -- Основная заработная плата.
- ОС -- Операционная система.
- ПК -- Персональный компьютер.
- ПО -- Программное обеспечение.
- ПС -- Программное средство.
- ПЭВМ -- Персональная электронная вычислительная машина.
- РОТ -- Расходы на оплату труда.
- СВ -- Страховые взносы.
- СУБД -- Система управления базами данных.
- СанПиН -- Санитарные правила, нормы, правила и нормы, гигиенические нормативы.
- ЧДД -- Чистый дисконтированный доход.
- ЭВМ -- Электронная вычислительная машина.
- з/п -- Заработная плата.
