package wassel:postgres;

interface postgres {
  resource connection-config {
    constructor(connection-string: string);
  }

  resource connection {
    open: static func(config: connection-config) -> result<connection, error>;
    query: func(sql: string, params: list<parameter>) -> result<row-set, error>;
    execute: func(sql: string, params: list<parameter>) -> result<u64, error>;
  }

  type decimal = string;

  record uuid { d1: u32, d2: u16, d3: u16, d4: u64 }
  record date { year: s32, month: u8, day: u8 }
  record time { hour: u8, minute: u8, second: u8, nanosecond: u32 }
  record datetime { date: date, time: time, offset: option<s16> }
  record interval { months: s32, days: s32, microseconds: s64 }
  enum range-bound { included, excluded, unbounded }

  record range-int32 {
    begin: option<s32>,
    begin-bound: range-bound,
    end: option<s32>,
    end-bound: range-bound,
  }

  record range-int64 {
    begin: option<s64>,
    begin-bound: range-bound,
    end: option<s64>,
    end-bound: range-bound,
  }

  record range-decimal {
    begin: option<decimal>,
    begin-bound: range-bound,
    end: option<decimal>,
    end-bound: range-bound,
  }

  record point { x: f64, y: f64 }
  record circle { x: f64, y: f64, radius: f64 }
  record line { a: f64, b: f64, c: f64 }
  record line-segment { start: point, end: point }
  record path { closed: bool, points: list<point> }
  record polygon { points: list<point> }

  variant cube {
    point(f64),
    zero-volume(list<f64>),
    one-dimension-interval(tuple<f64, f64>),
    multi-dimensional(list<list<f64>>),
  }

  variant data-type {
    boolean,
    int16,
    int32,
    int64,
    float32,
    float64,
    decimal,
    money,
    uuid,
    text,
    binary,
    date,
    time,
    datetime,
    interval,
    range-int32,
    range-int64,
    range-decimal,
    array-int32,
    array-int64,
    array-decimal,
    array-str,
    jsonb,
    hstore,
    point,
    circle,
    line,
    line-segment,
    path,
    polygon,
    cube,
    pg-null,
    other(string)
  }

  variant value {
    boolean(bool),
    int16(s16),
    int32(s32),
    int64(s64),
    float32(f32),
    float64(f64),
    decimal(decimal),
    money(s64),
    uuid(uuid),
    text(string),
    binary(list<u8>),
    date(date),
    time(time),
    datetime(datetime),
    interval(interval),
    range-int32(range-int32),
    range-int64(range-int64),
    range-decimal(range-decimal),
    array-int32(list<option<s32>>),
    array-int64(list<option<s64>>),
    array-decimal(list<option<decimal>>),
    array-str(list<option<string>>),
    jsonb(list<u8>),
    hstore(list<tuple<string, option<string>>>),
    point(point),
    circle(circle),
    line(line),
    line-segment(line-segment),
    path(path),
    polygon(polygon),
    cube(cube),
    pg-null,
    other(list<u8>),
  }

  type parameter = value;
  type row = list<value>;

  record row-set {
    columns: list<column>,
    rows: list<row>,
  }

  record column {
    name: string,
    data-type: data-type,
  }

  variant error {
    database(database-error),
    query(string),
    other(string),
  }

  record database-error {
    severity: string,
    parsed-severity: option<severity>,
    code: string,
    message: string,
    detail: option<string>,
    hint: option<string>,
    position: option<error-position>,
    where: option<string>,
    schema: option<string>,
    table: option<string>,
    column: option<string>,
    datatype: option<string>,
    constraint: option<string>,
    file: option<string>,
    line: option<u32>,
    routine: option<string>,
  }

  variant severity {
    panic,
    fatal,
    error,
    warning,
    notice,
    debug,
    info,
    log,
  }

  variant error-position {
    original(u32),
    internal(error-position-internal),
  }

  record error-position-internal {
    position: u32,
    query: string,
  }
}
