@startuml
skinparam classAttributeIconSize 0

class NString {
    -string : std::unique_ptr<const char[]>
    -<<static>> cstr_concatenation(str_a : char*, *str_b : char*) : char*
    -<<static>> trimChar(c : char ) : char*

    +NString(string : char*) : NString
    +get() : char*
    +size() : size_t
    +capitalize() : NString
    +to_lowercase() : NString
    +concatenate(second_string : NString) : NString
    +fill(char new_symbol) : NString
    +reverse() : NString
    +caesar_cypher(amount : int) : NString
    +replace_numbers(new_symbol : char) : NString
    +operator+(right : NString&) : NString
}

@enduml