@startuml
'https://plantuml.com/class-diagram
skinparam classAttributeIconSize 0

class Matrix {
    -m_matrix: vec2d
    -m_determinant: double
--
..Operators..
    +operator[](index: int): Row

    +operator<<(os: ostream&, const matrix: Matrix&): ostream&

    +operator==(const matrix_a: Matrix&, const matrix_b: Matrix& ): bool
    +operator!=(const matrix_a: Matrix&, const matrix_b: Matrix&): bool

    +operator+(const matrix_a: Matrix&, const matrix_b: Matrix&): Matrix
    +operator-(const matrix_a: Matrix&, const matrix_b: Matrix&): Matrix

    +operator*(const matrix: Matrix&, num: double): Matrix
    +operator*(num: double, const matrix: Matrix&): Matrix
    +operator*(const matrix_a: Matrix&, const matrix_b: Matrix&): Matrix

..Properties..
    +getRows(): size_t
    +getCols(): size_t
    +getDeterminant(): double
.. Private helper methods ..
    -static bool check_vec(const vec2d& vec);
    -static double getProductElement(vec2d vec_a, vec2d vec_b, int row, int col);
    -double evaluate_determinant() const;
}

class Row {
    +operator[](index: int): double
    -m_vec: std::vector<double>
}

Matrix +-.- Row

@enduml