#ifndef WASSEL_BINDINGS_H_
#define WASSEL_BINDINGS_H_

/* Generated with cbindgen:0.29.3 */

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

typedef enum wassel_HttpHandleResult {
  Success,
  Failure,
} wassel_HttpHandleResult;

typedef enum wassel_HttpMethod {
  Get,
  Post,
} wassel_HttpMethod;

typedef struct wassel_Stack wassel_Stack;

typedef struct wassel_HttpHeaderMap {
  const char *const *keys;
  const char *const *values;
  size_t count;
} wassel_HttpHeaderMap;

typedef struct wassel_HttpBody {
  const uint8_t *data;
  size_t length;
} wassel_HttpBody;

typedef struct wassel_HttpRequest {
  enum wassel_HttpMethod method;
  const char *path;
  struct wassel_HttpHeaderMap headers;
  struct wassel_HttpBody body;
} wassel_HttpRequest;

typedef struct wassel_HttpResponse {
  unsigned int status;
  struct wassel_HttpHeaderMap headers;
  struct wassel_HttpBody body;
} wassel_HttpResponse;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

void wassel_init(void);

void wassel_deinit(void);

struct wassel_Stack *wassel_stack_load(const char *path);

void wassel_stack_unload(struct wassel_Stack *stack);

enum wassel_HttpHandleResult wassel_stack_handle(struct wassel_Stack *stack,
                                                 struct wassel_HttpRequest *request,
                                                 struct wassel_HttpResponse *response);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* WASSEL_BINDINGS_H_ */
