#show figure: set block(breakable: true)
#counter(figure.where(kind: table)).update(0)

#figure(
  caption: [Матрица инструкций микропроцессора MOS6502],
  table(
    columns: 17,
    align: center,
    table.header(
      [*HI*],
      table.cell(colspan: 16)[*LO-NIBBLE*],
      [], [*-0*], [*-1*], [*-2*], [*-3*], [*-4*], [*-5*], [*-6*], [*-7*],
      [*-8*], [*-9*], [*-A*], [*-B*], [*-C*], [*-D*], [*-E*], [*-F*],
    ),

    [*0-*],
    [BRK impl],
    [ORA X,ind],
    [],
    [],
    [],
    [ORA zpg],
    [ASL zpg],
    [],
    [PHP impl],
    [ORA \#],
    [ASL A],
    [],
    [],
    [ORA abs],
    [ASL abs],
    [],

    [*1-*],
    [BPL rel],
    [ORA ind,Y],
    [],
    [],
    [],
    [ORA zpg,X],
    [ASL zpg,X],
    [],
    [CLC impl],
    [ORA abs,Y],
    [],
    [],
    [],
    [ORA abs,X],
    [ASL abs,X],
    [],

    [*2-*],
    [JSR abs],
    [AND X,ind],
    [],
    [],
    [BIT zpg],
    [AND zpg],
    [ROL zpg],
    [],
    [PLP impl],
    [AND \#],
    [ROL A],
    [],
    [BIT abs],
    [AND abs],
    [ROL abs],
    [],

    [*3-*],
    [BMI rel],
    [AND ind,Y],
    [],
    [],
    [],
    [AND zpg,X],
    [ROL zpg,X],
    [],
    [SEC impl],
    [AND abs,Y],
    [],
    [],
    [],
    [AND abs,X],
    [ROL abs,X],
    [],

    [*4-*],
    [RTI impl],
    [EOR X,ind],
    [],
    [],
    [],
    [EOR zpg],
    [LSR zpg],
    [],
    [PHA impl],
    [EOR \#],
    [LSR A],
    [],
    [JMP abs],
    [EOR abs],
    [LSR abs],
    [],

    [*5-*],
    [BVC rel],
    [EOR ind,Y],
    [],
    [],
    [],
    [EOR zpg,X],
    [LSR zpg,X],
    [],
    [CLI impl],
    [EOR abs,Y],
    [],
    [],
    [],
    [EOR abs,X],
    [LSR abs,X],
    [],

    [*6-*],
    [RTS impl],
    [ADC X,ind],
    [],
    [],
    [],
    [ADC zpg],
    [ROR zpg],
    [],
    [PLA impl],
    [ADC \#],
    [ROR A],
    [],
    [JMP ind],
    [ADC abs],
    [ROR abs],
    [],

    [*7-*],
    [BVS rel],
    [ADC ind,Y],
    [],
    [],
    [],
    [ADC zpg,X],
    [ROR zpg,X],
    [],
    [SEI impl],
    [ADC abs,Y],
    [],
    [],
    [],
    [ADC abs,X],
    [ROR abs,X],
    [],

    [*8-*],
    [],
    [STA X,ind],
    [],
    [],
    [STY zpg],
    [STA zpg],
    [STX zpg],
    [],
    [DEY impl],
    [],
    [TXA impl],
    [],
    [STY abs],
    [STA abs],
    [STX abs],
    [],

    [*9-*],
    [BCC rel],
    [STA ind,Y],
    [],
    [],
    [STY zpg,X],
    [STA zpg,X],
    [STX zpg,Y],
    [],
    [TYA impl],
    [STA abs,Y],
    [TXS impl],
    [],
    [],
    [STA abs,X],
    [],
    [],

    [*A-*],
    [LDY \#],
    [LDA X,ind],
    [LDX \#],
    [],
    [LDY zpg],
    [LDA zpg],
    [LDX zpg],
    [],
    [TAY impl],
    [LDA \#],
    [TAX impl],
    [],
    [LDY abs],
    [LDA abs],
    [LDX abs],
    [],

    [*B-*],
    [BCS rel],
    [LDA ind,Y],
    [],
    [],
    [LDY zpg,X],
    [LDA zpg,X],
    [LDX zpg,Y],
    [],
    [CLV impl],
    [LDA abs,Y],
    [TSX impl],
    [],
    [LDY abs,X],
    [LDA abs,X],
    [LDX abs,Y],
    [],

    [*C-*],
    [CPY \#],
    [CMP X,ind],
    [],
    [],
    [CPY zpg],
    [CMP zpg],
    [DEC zpg],
    [],
    [INY impl],
    [CMP \#],
    [DEX impl],
    [],
    [CPY abs],
    [CMP abs],
    [DEC abs],
    [],

    [*D-*],
    [BNE rel],
    [CMP ind,Y],
    [],
    [],
    [],
    [CMP zpg,X],
    [DEC zpg,X],
    [],
    [CLD impl],
    [CMP abs,Y],
    [],
    [],
    [],
    [CMP abs,X],
    [DEC abs,X],
    [],

    [*E-*],
    [CPX \#],
    [SBC X,ind],
    [],
    [],
    [CPX zpg],
    [SBC zpg],
    [INC zpg],
    [],
    [INX impl],
    [SBC \#],
    [NOP impl],
    [],
    [CPX abs],
    [SBC abs],
    [INC abs],
    [],

    [*F-*],
    [BEQ rel],
    [SBC ind,Y],
    [],
    [],
    [],
    [SBC zpg,X],
    [INC zpg,X],
    [],
    [SED impl],
    [SBC abs,Y],
    [],
    [],
    [],
    [SBC abs,X],
    [INC abs,X],
    [],
  ),
) <table-instructions>

#pagebreak()

#figure(
  table(
    columns: (auto, auto, auto, auto, 1fr),
    align: (center, center, center, center, left),

    table.header([*Режим*], [*Название*], [*Размер, байт*], [*Синтаксис*], [*Описание*]),

    [A], [Accumulator], [1], [`OPC A`], [операнд — аккумулятор (однобайтовая инструкция)],

    [abs], [absolute], [3], [`OPC $LLHH`], [операнд — адрес \$HHLL],

    [abs,X], [absolute, X-indexed], [3], [`OPC $LLHH,X`], [операнд — адрес; эффективный адрес = адрес + X с переносом],

    [abs,Y], [absolute, Y-indexed], [3], [`OPC $LLHH,Y`], [операнд — адрес; эффективный адрес = адрес + Y с переносом],

    [\#], [immediate], [2], [`OPC #$BB`], [операнд — байт BB],

    [impl], [implied], [1], [`OPC`], [операнд подразумевается],

    [ind], [indirect], [3], [`OPC ($LLHH)`], [операнд — адрес; эффективный адрес — содержимое слова по адресу: C.w(\$HHLL)],

    [X,ind],
    [X-indexed, indirect],
    [3],
    [`OPC ($LL,X)`],
    [операнд — адрес в нулевой странице; эффективный адрес — слово в (LL + X, LL + X + 1) без переноса: C.w(\$00LL + X)],

    [ind,Y],
    [indirect, Y-indexed],
    [3],
    [`OPC ($LL),Y`],
    [операнд — адрес в нулевой странице; эффективный адрес — слово в (LL, LL + 1) + Y с переносом: C.w(\$00LL) + Y],

    [rel], [relative], [2], [`OPC $BB`], [адрес перехода = PC + знаковое смещение BB],

    [zpg], [zeropage], [2], [`OPC $LL`], [операнд — адрес в нулевой странице (старший байт = 0, адрес = \$00LL)],

    [zpg,X],
    [zeropage, X-indexed],
    [2],
    [`OPC $LL,X`],
    [операнд — адрес в нулевой странице; эффективный адрес = адрес + X без переноса],

    [zpg,Y],
    [zeropage, Y-indexed],
    [2],
    [`OPC $LL,Y`],
    [операнд — адрес в нулевой странице; эффективный адрес = адрес + Y без переноса],
  ),
  caption: [Режимы адресации микропроцессора MOS6502],
) <table-addess-modes>
