# fly.toml app configuration file generated for cg-labs on 2025-01-06T00:40:12+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'cg-labs'

[build]

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
