[build]
target = "index.html"
dist = "dist"

[watch]
watch = [
    "src",
    "../course-project/src",
    "../framework/src",
    "../lab1/src",
    "../lab2/src",
    "../lab3/src",
]

[[hooks]]
stage = "pre_build"
command = "stylance"
command_arguments = ["."]
