[course]
faculty = "Автоматизация и интеллектуальные технологии"
department = "Информационные и вычислительные системы"
speciality = "Информатика и вычислительная техника"
profile = "Программное обеспечение средств вычислительной техники и автоматизированных систем"
year = 2026

[student]
name = "А. Шефнер"
group = "ИВБ-211"

[teacher]
name = "А.М. Барановский"
post = "Доц. каф. «ИВС»"

[industrial-placement]
title = "ПРЕДДИПЛОМНАЯ ПРАКТИКА"
code = "Б2.П.В.2"
